version: '3'

services:

  mysql:
    image: jichangfeng/docker-compose-laravel:mysql
    build:
      context: ./mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./code/:/var/www/code
    command: --default-authentication-plugin=mysql_native_password --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - MYSQL_ROOT_PASSWORD=nosmoking
      - TZ=Asia/Shanghai
    ports:
      - "33060:3306"

  postgres:
    image: jichangfeng/docker-compose-laravel:postgres
    build:
      context: ./postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./code/:/var/www/code
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nosmoking
      - TZ=Asia/Shanghai
    ports:
      - "54320:5432"

  redis:
    image: jichangfeng/docker-compose-laravel:redis
    build:
      context: ./redis
    volumes:
      - redis-data:/data
      - ./conf/redis/redis.conf:/usr/local/etc/redis.conf
      - ./redis/redis-check-aof.sh:/usr/local/bin/redis-check-aof.sh
    command: bash -c "chmod +x /usr/local/bin/redis-check-aof.sh
      && /usr/local/bin/redis-check-aof.sh
      && /usr/local/bin/redis-server /usr/local/etc/redis.conf"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "63790:6379"

  phpredisadmin:
    image: jichangfeng/docker-compose-laravel:phpredisadmin
    build:
      context: ./phpredisadmin
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USER=admin
      - ADMIN_PASS=nosmoking
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    ports:
      - "6380:6380"
    depends_on:
      - redis

  beanstalkd:
    image: jichangfeng/docker-compose-laravel:beanstalkd
    build:
      context: ./beanstalkd
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "11300:11300"

  beanstalkd-console:
    image: jichangfeng/docker-compose-laravel:beanstalkd-console
    build:
      context: ./beanstalkd-console
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
      - AUTH=enable
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=nosmoking
      - BEANSTALKD_PORT_11300_TCP_ADDR=beanstalkd
    ports:
      - "2080:2080"
    depends_on:
      - beanstalkd

  gearmand:
    image: jichangfeng/docker-compose-laravel:gearmand
    build:
      context: ./gearmand
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "4730:4730"
    command: ["--queue-type=redis", "--redis-server=redis", "--redis-port=6379"]

  php-fpm:
    image: jichangfeng/docker-compose-laravel:php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./conf/php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./code/:/var/www/code
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai

  php-cli:
    image: jichangfeng/docker-compose-laravel:php-cli
    build:
      context: ./php-cli
    volumes:
      - ~/.ssh/:/root/.ssh
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./code/:/var/www/code
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai

  nginx:
    image: jichangfeng/docker-compose-laravel:nginx
    build:
      context: ./nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d
      - ./conf/nginx/ssl/:/etc/nginx/ssl
      - ./logs/:/var/log/nginx
      - ./code/:/var/www/code
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:80"
      - "44300:443"
    depends_on:
      - php-fpm

  composer:
    image: jichangfeng/docker-compose-laravel:php-cli
    build:
      context: ./php-cli
    volumes:
      - ~/.ssh/:/root/.ssh
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./code/:/var/www/code
    working_dir: /var/www/code
    entrypoint: ['composer']
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai

  node:
    image: jichangfeng/docker-compose-laravel:node
    build:
      context: ./node
    volumes:
      - ./code/:/var/www/code
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Asia/Shanghai

volumes:
  mysql-data: 
  postgres-data: 
  redis-data: 
